version: '3'

x-redis: &common
  image: redis
  restart: on-failure
  command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

services:
  node-1:
    <<: *common
    container_name: node-1
    volumes:
      - ./node1/data:/data
      - ./node1/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.27.0.11

  node-2:
    <<: *common
    container_name: node-2
    volumes:
      - ./node2/data:/data
      - ./node2/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.27.0.12

  node-3:
    <<: *common
    container_name: node-3
    volumes:
      - ./node3/data:/data
      - ./node3/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.27.0.13

  node-4:
    <<: *common
    container_name: node-4
    volumes:
      - ./node4/data:/data
      - ./node4/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.27.0.14

  node-5:
    <<: *common
    container_name: node-5
    volumes:
      - ./node5/data:/data
      - ./node5/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.27.0.15

  node-6:
    <<: *common
    container_name: node-6
    volumes:
      - ./node6/data:/data
      - ./node6/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.27.0.16

networks:
  redis-cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24